HUMANPAGES_BASE_URL = "https://humanpages.ai"

SEARCH_HUMANS_ENDPOINT = "/api/humans/search"
CREATE_JOB_ENDPOINT = "/api/jobs"
JOB_STATUS_ENDPOINT = "/api/jobs/{job_id}"
JOB_MESSAGES_ENDPOINT = "/api/jobs/{job_id}/messages"

DEFAULT_TIMEOUT_SECONDS = 120
DEFAULT_PRICE_USDC = 5.0
DEFAULT_DEADLINE_HOURS = 24
DEFAULT_POLL_INTERVAL_SECONDS = 30
DEFAULT_MAX_POLL_ATTEMPTS = 120

AGENTQL_EXTRACT_DATA_ENDPOINT = "https://api.agentql.com/v1/query-data"
AGENTQL_DEFAULT_MODE = "fast"
AGENTQL_DEFAULT_TIMEOUT_SECONDS = 900

REQUEST_ORIGIN = "humanpages"
